// <auto-generated />
namespace Street_Vendors.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mapfore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mapfore));
        
        string IMigrationMetadata.Id
        {
            get { return "202103212022408_mapfore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
